# Trigger the workflow on push or pull request
on:
  workflow_call:
  pull_request:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/build.yml"
      - "action.yaml"
      - "entrypoint.sh"
      - "Dockerfile"
      - "test-site/**"

name: Build
jobs:
  build-1:
    name: Build with minimal options
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build with the latest action rev
        uses: cybardev/zola-deploy-action@main
        env:
          BUILD_ONLY: true
          BUILD_DIR: test-site
  build-2:
    needs: build-1
    name: Build with BUILD_FLAGS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build with the latest action rev
        uses: cybardev/zola-deploy-action@main
        env:
          BUILD_ONLY: true
          BUILD_DIR: test-site
          BUILD_FLAGS: --drafts --base-url example.com
  build-3:
    needs: build-2
    name: Build with CHECK_LINKS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build with the latest action rev
        uses: cybardev/zola-deploy-action@main
        env:
          BUILD_ONLY: true
          BUILD_DIR: test-site
          CHECK_LINKS: true
  build-4:
    needs: build-3
    name: Build with CHECK_LINKS and CHECK_FLAGS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build with the latest action rev
        uses: cybardev/zola-deploy-action@main
        env:
          BUILD_ONLY: true
          BUILD_DIR: test-site
          CHECK_LINKS: true
          CHECK_FLAGS: --drafts
