# Trigger the workflow on push or pull request
on:
  workflow_call:
  pull_request:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/main.yml"
      - "entrypoint.sh"

name: Test
jobs:
  test:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Shellcheck
        uses: docker://koalaman/shellcheck:latest
        with:
          args: ./entrypoint.sh
