# Create release on tagged push
on:
  push:
    tags:
      - "v*"

name: Release
jobs:
  run-main:
    uses: ./.github/workflows/main.yml

  run-build:
    needs: run-main
    uses: ./.github/workflows/build.yml

  publish-release:
    needs: run-build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
